### PR TITLE
feat:button page done

### PR DESCRIPTION
**Pull request by Developers-codz**

### CODE REVIEW

**Comment by BalajiHarinath** [comment]
.float{
    z-index:999
}
kajal may I know the why you have used z-index : 999 (like why such a huge number).
The other thing is could you please try to reduce the number of classes you have used for the button component (just a suggestion).
Apart from these rest of the things look good to me.

**Review by foolhardy21 — APPROVED** [review]
LGTM. Just one suggestion. you can make the social media handle icons a bit darker. they'll be easy to spot.

**Comment by Developers-codz** [comment]
> 
thinking it's a float button so it should appear on top at any circumstances that's why I used but ok I will decrease the value.
Also I will try minimizing classes.
thanks for reviewing :)

**Comment by Developers-codz** [comment]
> LGTM. Just one suggestion. you can make the social media handle icons a bit darker. they'll be easy to spot.

will look into that. Thanks for reviewing :)

**Comment by Developers-codz** [comment]
> .float{ z-index:999 } kajal may I know the why you have used z-index : 999 (like why such a huge number). The other thing is could you please try to reduce the number of classes you have used for the button component (just a suggestion). Apart from these rest of the things look good to me.

thinking it's a float button so it should appear on top at any circumstances that's why I used but ok I will decrease the value.
Also I will try minimizing classes.
thanks for reviewing :)

**Review by shahbazibnafzal — APPROVED** [review]
looks good Kajal

**Review by BalajiHarinath — APPROVED** [review]

**Pull request merged**
