### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by Developers-codz**
Updated Readme 
Live https://github.com/Developers-codz/beadUI/tree/docs#readme

Thank you for PR review :)

### CODE REVIEW

**Review by vishalg8454 — APPROVED** [review]

**Review by arjun-computer-geek — APPROVED** [review]
looks good to me

**Review by b0llu — APPROVED** [review]
Good job on adding a visual clip for the library

**Comment by vashnavichauhan1825** [comment]
approved for merge

**Review by vashnavichauhan1825 — APPROVED** [review]
approved for merge

**Pull request merged**
